# Helper scripts and utilities
_ANSIBLE_PLAYBOOK ?= ansible-playbook
_APT_GET ?= $(shell $(_COMMAND) -v apt-get)
_BIN ?= ./bin
_COMMAND ?= command
_DATE ?= date
_DD ?= dd
_ECHO ?= echo
_GREP ?= grep
_GZIP ?= gzip
_LN ?= ln
_MOUNT ?= mount
_RPI_IMAGER ?= rpi-imager
_SED ?= sed
_SHA256SUM ?= sha256sum
_SUDO ?= sudo
_TEE ?= tee
_TEST ?= test
_TOUCH ?= touch
_UMOUNT ?= umount
_UNLINK ?= unlink
